version: "3.8"

services:
  next-server:
    build:
      context: ./feedback
    container_name: next-app
    ports:
      - "3000:3000"
    # env_file:
    #   - ./feedback/.env
    environment:
      - MAIL_SERVER_URL=http://queue-server:3001
    networks:
      - my-network

  queue-server:
    build:
      context: ./queue-server
    container_name: queue-server
    ports:
      - "3001:3001"
    # env_file:
    #   - ./queue-server/.env
    networks:
      - my-network

networks:
  my-network:
    driver: bridge